# Generated by Django 4.0.3 on 2022-10-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Должности')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='job_title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.job_title'),
            preserve_default=False,
        ),
    ]
