# Generated by Django 4.0.3 on 2022-10-31 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_worker_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='job_title',
        ),
        migrations.DeleteModel(
            name='Job_title',
        ),
    ]
