# Generated by Django 4.0.3 on 2022-10-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_worker_job_title_delete_job_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
