# Generated by Django 4.0.3 on 2022-11-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'Оценка качества', 'verbose_name_plural': 'Оценка качества'},
        ),
    ]
