# Generated by Django 4.0.3 on 2022-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_quality_feasibility_alter_quality_flexibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='date',
            field=models.DateField(verbose_name='Дата оценки'),
        ),
    ]
